In [3]:
import numpy as np

In [4]:
print(np.__version__)
np.__config__.show()

1.21.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512C

In [5]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:

print(zeros.size)
print(zeros.itemsize)
size_bytes = zeros.size * zeros.itemsize
print(f"The total size of the zeros array is {zeros.size * zeros.itemsize} bytes.")

10
8
The total size of the zeros array is 80 bytes.


You have to call np.info(np.add)

In [15]:
zeros_b = zeros.copy()
print(zeros_b)
zeros_b[4] = 1
print(zeros_b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
matrix = np.array((np.arange(0,9))).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
array = np.array([1,2,0,0,4,0])
indexes = array.nonzero()
print(indexes)
print(np.nonzero(array))

(array([0, 1, 4], dtype=int64),)
(array([0, 1, 4], dtype=int64),)


In [15]:
identity_mat = np.eye(3,3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
random_3d = np.random.random((3,3,3))
print(random_3d)

[[[0.38509925 0.95108138 0.36748993]
  [0.74057012 0.77730116 0.57804589]
  [0.15839759 0.62957207 0.98147853]]

 [[0.82167516 0.13487496 0.03149215]
  [0.19074737 0.14937086 0.73084408]
  [0.89402693 0.22446622 0.27892498]]

 [[0.66695686 0.20670464 0.45861862]
  [0.79694379 0.35975111 0.7190472 ]
  [0.12308977 0.38566959 0.17001388]]]


In [18]:
random_2d = np.random.random((10,10))
print(random_2d.min())
print(random_2d.max())

0.0027510261692070825
0.9987415329685921


In [20]:
random_v = np.random.random(10)
print(random_v.mean())

0.4189749575597027


### 15.- Create an array with one on the borders and zeros inside

In [23]:
matrix = np.ones((10,10))
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array?


In [33]:
existing = np.random.random((10,10))
padded = np.pad(existing, 1,mode="constant", constant_values=0)
print(padded)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.99215456 0.15495383 0.52727347 0.5478037  0.65160521
  0.90032421 0.96901842 0.32064608 0.72750278 0.86540741 0.        ]
 [0.         0.11259508 0.80649262 0.96771155 0.64892664 0.57448444
  0.40767837 0.9263524  0.674665   0.72030341 0.90143137 0.        ]
 [0.         0.370159   0.41236676 0.24695687 0.82566611 0.59001248
  0.00182536 0.132853   0.10571105 0.98621759 0.76761056 0.        ]
 [0.         0.6240852  0.20975018 0.1684676  0.51418374 0.36448379
  0.28706883 0.59493101 0.07753574 0.87471704 0.52464554 0.        ]
 [0.         0.98537685 0.63960237 0.54779743 0.64363468 0.28811977
  0.05673139 0.12055665 0.34926837 0.73613382 0.87720296 0.        ]
 [0.         0.96641638 0.90843446 0.63957964 0.67224746 0.11707894
  0.32720087 0.71032134 0.72845198 0.89914259 0.48984818 0.        ]
 [0.         0.20699041 0.81522056 0.10264971 0.0

### 17. What is the result of the following expression?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

In [41]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [47]:

array = np.diag(np.arange(1,5), -1)
print(array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [60]:
mat_a = np.zeros((8,8))
mat_a[::2,::2] = 1
mat_a[1::2,1::2] = 1
print(mat_a)
#indexes = [index % 2 for index, x in enumerate(range(8))]


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [67]:
array = np.random.random((6,7,8))
print(array[np.unravel_index(100, (6,7,8))])

0.9263780381081932


### 21. Create a checkerboard 8x8 matrix using the tile function

In [75]:
a = np.tile(([0,1],[1,0]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix

In [77]:
mat = np.random.random((5,5))

mat = (mat-mat.mean())/mat.std()
print(mat)

[[-0.44811137  0.21599282 -1.26021678  0.61420724  1.65080989]
 [ 0.56300065  1.27776845 -0.55682186 -1.03255538 -1.03951439]
 [-0.57908146 -0.02137006  1.00439194 -1.21224531 -0.95527949]
 [-0.91207891  1.24960923  1.27968936 -0.85713306  0.06465176]
 [-0.79949367  1.43470952  1.72576987 -0.20652462 -1.20017437]]


### 23. Create a custom dtype that describes a color as four unsigned bytes

In [86]:
dt = np.dtype([('r', np.dtype("i1")),('g', np.dtype("i1")), ('b', np.dtype("i1")), ('a', np.dtype("i1"))])
a = np.array((6,3,4, 8), dtype=dt)
print(a)

(6, 3, 4, 8)
